CREATE TABLE IF NOT EXISTS Sales.SalesOrderHeader
(
SalesOrderID INT(5) NOT NULL,
RevisionNumber INT(1),
OrderDate DATE,
DueDate DATE,
ShipDate DATE,
Status INT(1),
OnlineOrderFlag INT(1),
SalesOrderNumber VARCHAR(7),
PurchaseOrderNumber VARCHAR(13),
AccountNumber VARCHAR(14),
CustomerID INT(5),
SalesPersonID INT(5),
TerritoryID INT(2),
BillToAddressID INT(5),
ShipToAddressID INT(5),
ShipMethodID INT(1),
CreditCardID INT(7),
CreditCardApprovalCode VARCHAR(15),
CurrencyRateID INT(7),
SubTotal FLOAT,
TaxAmt FLOAT,
Freight FLOAT,
TotalDue FLOAT,
Comment VARCHAR(3),
rowguid VARCHAR(36),
ModifiedDate DATETIME,
PRIMARY KEY (SalesOrderID),
FOREIGN KEY (CustomerID) REFERENCES Sales.Customer(CustomerID)
)