CREATE TABLE IF NOT EXISTS testeRox.Product
(
ProductID INT NOT NULL,
Name VARCHAR(255),
ProductNumber VARCHAR(255),
MakeFlag INT,
FinishedGoodsFlag INT,
Color VARCHAR(255),
SafetyStockLevel INT,
ReorderPoint INT,
StandardCost FLOAT,
ListPrice FLOAT,
Size VARCHAR(255),
SizeUnitMeasureCode VARCHAR(255),
WeightUnitMeasureCode VARCHAR(255),
Weight FLOAT,
DaysToManufacture INT,
ProductLine VARCHAR(255),
Class VARCHAR(255),
Style VARCHAR(255),
ProductSubcategoryID INT,
ProductModelID INT,
SellStartDate DATETIME,
SellEndDate DATETIME,
DiscontinuedDate DATETIME,
rowguid VARCHAR(255),
ModifiedDate DATETIME,
PRIMARY KEY (ProductID)
)