CREATE TABLE IF NOT EXISTS testeRox.SalesOrderHeader
(
SalesOrderID INT NOT NULL,
RevisionNumber INT,
OrderDate DATETIME,
DueDate DATETIME,
ShipDate DATETIME,
Status INT,
OnlineOrderFlag INT,
SalesOrderNumber VARCHAR(255),
PurchaseOrderNumber VARCHAR(255),
AccountNumber VARCHAR(255),
CustomerID INT,
SalesPersonID INT,
TerritoryID INT,
BillToAddressID INT,
ShipToAddressID INT,
ShipMethodID INT,
CreditCardID INT,
CreditCardApprovalCode VARCHAR(255),
CurrencyRateID INT,
SubTotal FLOAT,
TaxAmt FLOAT,
Freight FLOAT,
TotalDue FLOAT,
Comment VARCHAR(255),
rowguid VARCHAR(255),
ModifiedDate DATETIME,
PRIMARY KEY (SalesOrderID)
)